# Generated by Django 2.2 on 2020-10-16 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamLearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='test_field',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_change_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_change_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='validate_code',
        ),
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, default='/TeamLearning/team_avatars/default_avatar.png', null=True, upload_to='TeamLearning/team_avatars/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название команды'),
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(related_name='Teams', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='user',
            name='professionalism_coefficient',
            field=models.IntegerField(default=5, verbose_name='Коэффициент профессионализма'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, null=True, verbose_name='Никнейм (показывается на сайте)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/TeamLearning/user_avatars/default_avatar.png', null=True, upload_to='TeamLearning/user_avatars/', verbose_name='Фото'),
        ),
    ]
