# Generated by Django 2.2 on 2020-10-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamLearning', '0002_auto_20201016_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор новости')),
                ('post_header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('post_text', models.TextField(verbose_name='Текст поста')),
                ('post_image', models.ImageField(blank=True, default='/TeamLearning/news_images/default_post_image.png', null=True, upload_to='TeamLearning/news_images/', verbose_name='Фото')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
            ],
        ),
    ]
