# Generated by Django 2.2 on 2020-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamLearning', '0004_auto_20201017_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Никнейм (показывается на сайте)'),
        ),
    ]
