# Generated by Django 2.2 on 2020-10-18 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamLearning', '0005_auto_20201017_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_teams', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='is_open',
            field=models.BooleanField(default=1, verbose_name='Открытое вступление?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='requests',
            field=models.ManyToManyField(related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявки'),
        ),
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, verbose_name='Название проекта/хакатона')),
                ('project_description', models.TextField(verbose_name='Описание проекта/хакатона')),
                ('start_date', models.DateField(verbose_name='Дата начала проекта')),
                ('dead_line', models.DateField(null=True, verbose_name='Дата начала проекта')),
                ('is_open', models.BooleanField(verbose_name='Открытая запись?')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_projects', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('requests', models.ManyToManyField(related_name='projects_request', to='TeamLearning.Team', verbose_name='Заявки на участие в проекте/хакатоне')),
                ('teams', models.ManyToManyField(related_name='projects', to='TeamLearning.Team', verbose_name='Команды')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
