# Generated by Django 2.2 on 2020-10-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamLearning', '0006_auto_20201018_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(null=True, verbose_name='Открытая запись?'),
        ),
    ]
