# Generated by Django 2.2 on 2020-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamLearning', '0007_auto_20201018_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Открытая запись?'),
        ),
    ]
